config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#index"
  resources :recipes do
  	resource :favorites, only: [:index, :create, :destroy]
  	resources :reviews, only: [:index, :create]
  	resources :comments, only: [:create, :destroy]
  end

  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :recipe
  #バリデーション
  validates :content, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
    belongs_to :recipe
    validates_uniqueness_of :recipe_id, scope: :user_id
end

app/models/recipe.rb
class Recipe < ApplicationRecord
	belongs_to :user
	has_many :recipe_images, dependent: :destroy
	accepts_attachments_for :recipe_images, attachment: :image
	has_many :reviews, dependent: :destroy
	has_many :favorites, dependent: :destroy
	has_many :comments, dependent: :destroy

	with_options presence: true do
		validates :title
		validates :body
	end
end

app/models/recipe_image.rb
class RecipeImage < ApplicationRecord
	belongs_to :recipe
	attachment :image

	validates :image, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image
  attachment :profile_bg_image
  validates :name, presence: true

  has_many :recipes, dependent: :destroy
  has_many :recipe_images, dependent: :destroy
  accepts_attachments_for :recipe_images, attachment: :image
  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def already_favorited?(recipe)
    self.favorites.exists?(recipe_id: recipe.id)
  end

  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

	private
	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@recipe = Recipe.find(params[:recipe_id])
		@comment = @recipe.comments.build(comment_params)
		@comment.user_id = current_user.id
		if @comment.save
			redirect_to @recipe
		else
			render 'recipes/show'
		end
	end

	def destroy
		@comment = Comment.find(params[:recipe_id])
		if @comment.destroy
			redirect_to recipe_path(@comment.recipe)
		end
	end

	private
	def comment_params
		params.require(:comment).permit(:content, :user_id, :recipe_id)
	end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	def create
		@favorite = current_user.favorites.create(recipe_id: params[:recipe_id])
		redirect_back(fallback_location: root_path)
	end

	def destroy
	    @recipe = Recipe.find(params[:recipe_id])
	    @favorite = current_user.favorites.find_by(recipe_id: @recipe.id)
	    @favorite.destroy
	    redirect_back(fallback_location: root_path)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
  	@recipes = Recipe.all
  end

  def show
  	@recipe = Recipe.find(params[:id])
    @review = Review.new
    @comment = Comment.new
    @comments = @recipe.comments.order(created_at: :desc)
  end

  def edit
  	@recipe = Recipe.find(params[:id])
    if @recipe.user != current_user
      redirect_to recipes_path, alert: "不正なアクセスです！"
    end
  end

  def update
  	@recipe = Recipe.find(params[:id])
  	if @recipe.update(recipe_params)
  	  redirect_to recipe_path(@recipe), notice: "更新に成功しました！"
    else
      render :edit
    end
  end

  def create
  	@recipe = Recipe.new(recipe_params)
  	@recipe.user_id = current_user.id
  	if @recipe.save
  	  redirect_to recipe_path(@recipe), notice: "投稿に成功しました！"
    else
      render :new
    end
  end

  def new
  	@recipe = Recipe.new
    @recipe.recipe_images.build
  end

  def destroy
    recipe = Recipe.find(params[:id])
    recipe.destroy
    redirect_to recipes_path
  end


  private
  def recipe_params
  	params.require(:recipe).permit(:title, :body, recipe_images_images: [])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
  	@users = User.all
  end

  def show
  	@user = User.find(params[:id])
  end

  def edit
  	@user = User.find(params[:id])
    if @user != current_user
      redirect_to users_path, alert: "不正なアクセスです！"
    end
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  	  redirect_to user_path(@user), notice: "更新に成功しました！"
    else
      render :edit
    end
  end


  private
  def user_params
  	params.require(:user).permit(:name, :email, :profile, :profile_image, :profile_bg_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: [recipe, comment], url: recipe_comments_path(@recipe) ) do |f| %>
    <%= f.text_area :content, class: "input-mysize" %>
    <%= f.submit "送信", class: "btn btn-outline-dark comment-submit float-right" %>
<% end %>

app/views/comments/_index.html.erb
<div class="col-6">
    <div class="comment-form">
        <h2 class="comment">コメント</h2>
        <!--引数の順番は親から子へ-->
        <%= form_for ([@recipe,@comment]) do |f| %>

        <div class="form-group">
            <%= f.text_area :content, class: "form-control", placeholder: "コメントしてみよう" %>
        </div>

        <div class="comment-button" style="margin-bottom: 35px">
            <%= f.submit "コメントする", class: "btn btn-info btn-block" %>
        </div>
        <%end%>
    </div>

    <h2 class="comment-index">コメント一覧</h2>

    <% @comments.each do |comment| %>

    <div class="card">
        <h5 class="card-header">
            <div class="comment-user-profile-image" style="border-radius: 50%;">
                <%= attachment_image_tag comment.user, :profile_image, :fill, 50, 50, fallback: "no-image.png", size: "50x50", class:"img-fluid" %>
                <%= link_to "#{comment.user.name}さん", user_path(comment.user.id) %>
                <time datetime="<%= comment.created_at %>" style="font-size: 13px;  margin-left: 222px">
                    <%= time_ago_in_words(comment.created_at) %>前
                </time>
            </div>
        </h5>

        <div class="card-body">
            <div class="card-text">
                <%= simple_format comment.content %>

                <% if comment.user == current_user %>
                <div class="card-button" style="text-align: right;">
                    <%= link_to recipe_comment_path(comment), method: :delete, data: {confirm:"本当に削除しますか？"} do %>
                    <span class="fa fa-trash trash-btn"></span>
                    <% end %>
                </div>
                <% end %>
            </div>
        </div>
    </div>
    <% end %>
</div>

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'index', { comments: @comment.recipe.comments }) %>")
$("textarea").val('')

app/views/homes/index.html.erb
<div class="row relative">
	<div class="col-12">
		<%= image_tag "top-bg-meal.jpg", class: "top-meal-bg" %>
	</div>

	<h2 class="top-bg-copy">
		『腹減った、、、』<br>
		『今日はウチでごはん食べたい気分、、、』<br>
		『ささっと出来て、おいしいごはんが食べたい、、、』<br>
	</h2>

	<h2 class="top-bg-copy-2">
		そんなあなたにウチでできる簡単レシピ、harahetterなら探せます
	</h2>
	<p class="top-bg-copy-3">harahetterは料理初心者でもウチで簡単にできるレシピが見つかります</p>
</div>

app/views/recipes/edit.html.erb
<div class="container mt-5">
	<div class="row">
		<div class="col-6 mx-auto">
			<h2 class="recipes-edit-title">
				レシピの編集
			</h2>

			<%= form_with model: @recipe do |form| %>

			<div class="form-group">
				<%= form.label :メニュー画像 %>
				<%= form.attachment_field :recipe_images_images, class: "form-control", multiple: true %>
			</div>

			<div class="form-group">
				<%= form.label :メニュー名 %>
				<%= form.text_field :title, class: "form-control" %>
			</div>

			<div class="form-group">
				<%= form.label :レシピ %>
				<%= form.text_area :body, size: "20x5", class: "form-control" %>
			</div>

			<div class="actions">
				<%= form.submit "投稿する", class: "btn btn-success btn-block" %>
			</div>
			<% end %>
		</div>
	</div>
</div>

app/views/recipes/index.html.erb
<div class="container mt-5">
	<div class="row">
		<div class="col-8 mx-auto">
			<h2 class="recipes-index-title">ハラヘリメニュー</h2>
			<table class="table table-hover">
				<thead class="index-title">
					<tr>
						<th scope="col">メニュー名</th>
						<th scope="col">写真</th>
						<th scope="col"></th>
						<th scope="col">投稿者</th>
					</tr>
				</thead>
				<tbody class="index-body">
					<% @recipes.each do |recipe| %>
					<tr>
						<td class="recipe-title">
							<%= link_to truncate(recipe.title, length: 12), recipe_path(recipe) %>
						</td>

						<td>
							<%= link_to recipe_path(recipe) do %>
							<%= attachment_image_tag recipe.recipe_images.first, :image, :fill, 100, 100, format: 'jpeg' %>
							<% end %>
						</td>

						<td class="recipes-index-favorites">
							<% if current_user.already_favorited?(recipe) %>
							  <%= link_to recipe_favorites_path(recipe), method: :delete do %>
							  <i class="fas fa-thumbs-up"></i>
							  <% end %>
							<% else %>
							  <%= link_to recipe_favorites_path(recipe), method: :post do %>
							  <i class="fa fa-thumbs-up"></i>
							  <% end %>
							<% end %>
							<%= recipe.favorites.count %>
						</td>

						<td class="recipe-username">
							<%= link_to recipe.user.name, user_path(recipe.user_id) %>
						</td>

					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/recipes/new.html.erb
<% if @recipe.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @recipe.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>



<div class="container mt-5">
	<div class="row">
		<div class="col-6 mx-auto">
			<h2 class="recipes-new-title">新規ハラヘリメニュー投稿</h2>

			<%= form_with model: @recipe, local: true do |form| %>
			<div class="form-group">
				<%= form.label :メニュー画像 %>
				<%= form.attachment_field :recipe_images_images, class: "form-control", multiple: true %>
			</div>

			<div class="form-group">
				<%= form.label :メニュー名 %>
				<%= form.text_field :title, class: "form-control" %>
			</div>

			<div class="form-group">
				<%= form.label :レシピ %>
				<%= form.text_area :body, size: "20x5", class: "form-control" %>
			</div>

			<div class="actions">
				<%= form.submit "投稿する", class: "btn btn-success btn-block" %>
			</div>
			<% end %>
		</div>
	</div>
</div>

app/views/recipes/show.html.erb
<div class="container mt-5">
	<div class="row">
		<div class="col-6">
			<h2 class="recipes-show-title" style="font-weight: bold; text-align: center;">
				<%= @recipe.title %>の詳細レシピ
			</h2>
			<div class="card">
				<div class="card-body">
					<h5 class="card-title">
						<%= @recipe.title %>
					</h5>

					<div class="card-image">
						<% if @recipe.recipe_images.present? %>
						<% @recipe.recipe_images.each do |recipe_image| %>
						<%= attachment_image_tag recipe_image, :image, :fill, 600, 550, format: 'jpeg', class:"img-fluid mx-auto"  %>
						<% end %>
						<% end %>
					</div>

					<p class="card-text">
						<%= simple_format @recipe.body %>
					</p>

					<% unless @recipe.user == current_user %>
					<p class="recipe-contributor">
						<%= link_to "このレシピの投稿者を見る", user_path(@recipe.user.id), class: "btn btn-success" %>
					</p>
					<% end %>

					<p class="card-text">
						<small class="text-muted">
							投稿日：<%= @recipe.created_at.strftime("%Y-%m-%d") %>
						</small>
					</p>

					<% if @recipe.user == current_user %>
					<!-- 記事を投稿した人とログインしている人が同じならば編集と削除を表示させる -->
					<div class="recipe-button" style="text-align: right;">
						<%= link_to "編集", edit_recipe_path(@recipe), class: "btn btn-success" %>
						<%= link_to "削除", recipe_path(@recipe), method: :delete, class: "btn btn-danger", data: {confirm: "本当に削除しますか？"} %>
					</div>
					<% end %>
				</div>
			</div>
		</div>

		<div class="col-6">
			<div class="comment-form">
				<h2 class="recipes-show-comments-title">コメント</h2>
				<!--引数の順番は親から子へ-->
				<%= form_for ([@recipe,@comment]) do |f| %>

				<div class="form-group">
					<%= f.text_area :content, size: "20x7", class: "form-control", placeholder: "コメントしてみよう" %>
				</div>

				<div class="comment-button">
					<%= f.submit "コメントする", class: "btn btn-success btn-block" %>
				</div>
				<%end%>
			</div>

			<h2 class="recipes-show-comments-catalog">コメント一覧</h2>

			<% @comments.each do |comment| %>

			<div class="card">
				<div class="card-body">
					<div class="comment-user-profile-image">
						<%= attachment_image_tag comment.user, :profile_image, :fill, 50, 50, fallback: "no-image.png", size: "50x50", class:"img-fluid" %>

						<%= link_to "#{comment.user.name}さん", user_path(comment.user.id), class: "comments-user-name" %>

						<time datetime="<%= comment.created_at %>" style="font-size: 13px;  margin-left: 222px">
							コメント投稿日：<%= comment.created_at.strftime("%Y-%m-%d") %>
						</time>
					</div>
					<div class="card-text">
						<%= simple_format comment.content %>

						<% if comment.user == current_user %>
						<div class="card-button" style="text-align: right;">
							<%= link_to recipe_comment_path(comment), method: :delete, data: {confirm:"本当に削除しますか？"} do %>
							<span class="fa fa-trash trash-btn"></span>
							<% end %>
						</div>
						<% end %>
					</div>
				</div>
			</div>
			<% end %>
		</div>
	</div>
</div>

app/views/reviews/_form.html.erb
<p class="mb-3">レビューを書く</p>


<div class="rating-box mt-3">
	<%= form_with model: review, url: recipe_reviews_path(recipe), local: true do |f| %>
	  <div class="main-rating">
		  <div class="ratings mb-3">
			  <span class="fa fa-star-o" id="star"></span>
			  <span class="fa fa-star-o" id="star"></span>
			  <span class="fa fa-star-o" id="star"></span>
			  <span class="fa fa-star-o" id="star"></span>
			  <span class="fa fa-star-o" id="star"></span>
		  </div>
		  <div class="ml-3 rating-value-display">
		  	<span id="rating-value-display">0</span>/5
		  </div>
	  </div>
	  <%= f.hidden_field :recipe_id, value: recipe.id %>
	  <%= f.hidden_field :score, id: "rating-value" %>
	  <%= f.text_area :content, class: "textarea" %>
	  <%= f.submit "保存", class: "btn btn-success" %>
	  <%= link_to "他のレビューを見る", recipe_reviews_path(recipe), class: "btn btn-success" %>
	<% end %>
</div>

app/views/reviews/index.html.erb
<h1>Reviews#index</h1>
<p>Find me in app/views/reviews/index.html.erb</p>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>


<div class="container mt-5">
	<div class="row">
		<div class="col-6 mx-auto">
			<h2 class="edit-users-title">ユーザー編集</h2>
			<%= form_with model: @user, local: true do |form| %>

			<div class="form-group">
				<%= form.label :プロフィール背景画像 %>
				<%= form.attachment_field :profile_bg_image, class: "form-control" %>
			</div>

			<div class="form-group">
				<%= form.label :プロフィール画像 %>
				<%= form.attachment_field :profile_image, class: "form-control" %>
			</div>

			<div class="form-group">
				<%= form.label :お名前 %>
				<%= form.text_field :name, class: "form-control" %>
			</div>

			<div class="form-group">
				<%= form.label :メールアドレス %>
				<%= form.email_field :email, class: "form-control" %>
			</div>

			<div class="form-group">
				<%= form.label :プロフィール %>
				<%= form.text_area :profile, class: "form-control" %>
			</div>

			<div class="actions">
				<%= form.submit "更新する", class: "btn btn-success btn-block" %>
			</div>
			<% end %>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<div class="container mt-5">
	<div class="row">
		<h2 class="index-users-title">ユーザー一覧</h2>
		<% @users.each do |user| %>
		<div class="col-3">
			<div class="card">
				<div class="card-body">
					<div class="card-content">
						<div class="card-image">
							<figure class="image">
								<%= link_to user_path(user) do %>
									<%= attachment_image_tag user, :profile_image, :fill, 260, 280, fallback: "no-image.png", class:"img-fluid" %>
								<% end %>
							</figure>
						</div>
					</div>
				</div>
				<div class="card-content">
					<div class="card-body">
						<div class="media">
							<div class="media-content">
								<div class="index-user-name">
									【 <%= link_to user.name, user_path(user) %> 】
									<small>投稿数：<%= user.recipes.count %> 件</small>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<div class="row">
	<div class="col-12">
		<div class="users-show-title">
			<div class="users-show-bg-image">
				<%= attachment_image_tag @user, :profile_bg_image, :fill, 1500, 300, fallback: "users-show-bg-image.jpg", class:"img-fluid" %>
			</div>
			<h1><%= @user.name %>のマイページ  </h1>
		</div>
	</div>
</div>

<div class="container mt-5">
	<div class="row">
		<div class="col-3">
			<div class="card">
				<div class="card-body">
					<%= attachment_image_tag @user, :profile_image, :fill, 250, 250, fallback: "no-image.png", class:"img-fluid" %>
				</div>
				<div class="content">
					<div class="card-body">
						<h5 class="card-title">
							【 <%= @user.name %> 】
						</h5>

						<% if @user.id == current_user.id %>
						<p class="card-content">
							<small class="text-muted">
								<%= @user.email %>
							</small>
						</p>
						<% end %>

						<p class="card-content-1">
							<small><%= @user.profile %></small>
						</p>

						<div class="show-btn">
							<% if @user.id == current_user.id %>
							<%= link_to "ユーザー情報を編集する", edit_user_path, class: "btn btn-primary" %>
							<% end %>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="col-9 mx-auto">
			<table class="table table-hover">
				<thead class="index-title">
					<tr>
						<th scope="col">【 メニュー名 】</th>
						<th scope="col">【 写真 】</th>
						<th scope="col">【 いいね数 】</th>
					</tr>
				</thead>
				<tbody class="index-body">
					<% @user.recipes.each do |recipe| %>
					<tr>
						<td class="recipe-title">
							<%= link_to truncate(recipe.title, length: 12), recipe_path(recipe) %>
						</td>

						<td>
							<%= link_to recipe_path(recipe) do %>
							<%= attachment_image_tag recipe.recipe_images.first, :image, :fill, 100, 100, format: 'jpeg' %>
							<% end %>
						</td>

						<td class="users-show-favorites">
							<%= recipe.favorites.count %>
						</td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>