config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#index"
  resources :recipes do
  	resource :favorites, only: [:index, :create, :destroy]
  	resources :reviews, only: [:index, :create]
  	resources :comments, only: [:create, :destroy]
  end

  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :recipe
  #バリデーション
  validates :content, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
    belongs_to :recipe
    validates_uniqueness_of :recipe_id, scope: :user_id
end

app/models/recipe.rb
class Recipe < ApplicationRecord
	belongs_to :user
	has_many :recipe_images, dependent: :destroy
	accepts_attachments_for :recipe_images, attachment: :image
	has_many :reviews, dependent: :destroy
	has_many :favorites, dependent: :destroy
	has_many :comments, dependent: :destroy

	with_options presence: true do
		validates :title
		validates :body
	end
end

app/models/recipe_image.rb
class RecipeImage < ApplicationRecord
	belongs_to :recipe
	attachment :image

	validates :image, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image
  attachment :profile_bg_image
  validates :name, presence: true

  has_many :recipes, dependent: :destroy
  has_many :recipe_images, dependent: :destroy
  accepts_attachments_for :recipe_images, attachment: :image
  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def already_favorited?(recipe)
    self.favorites.exists?(recipe_id: recipe.id)
  end

  has_many :comments, dependent: :destroy
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@recipe = Recipe.find(params[:recipe_id])
		@comment = @recipe.comments.build(comment_params)
		@comment.user_id = current_user.id
		if @comment.save
			redirect_to @recipe
		else
			render 'recipes/show'
		end
	end

	def destroy
		@comment = Comment.find(params[:recipe_id])
		if @comment.destroy
			redirect_to recipe_path(@comment.recipe)
		end
	end

	private
	def comment_params
		params.require(:comment).permit(:content, :user_id, :recipe_id)
	end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	def create
		@favorite = current_user.favorites.create(recipe_id: params[:recipe_id])
		redirect_back(fallback_location: root_path)
	end

	def destroy
	    @recipe = Recipe.find(params[:recipe_id])
	    @favorite = current_user.favorites.find_by(recipe_id: @recipe.id)
	    @favorite.destroy
	    redirect_back(fallback_location: root_path)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
  	@recipes = Recipe.all
  end

  def show
  	@recipe = Recipe.find(params[:id])
    @review = Review.new
    @comment = Comment.new
    @comments = @recipe.comments.order(created_at: :desc)
  end

  def edit
  	@recipe = Recipe.find(params[:id])
    if @recipe.user != current_user
      redirect_to recipes_path, alert: "不正なアクセスです！"
    end
  end

  def update
  	@recipe = Recipe.find(params[:id])
  	if @recipe.update(recipe_params)
  	  redirect_to recipe_path(@recipe), notice: "更新に成功しました！"
    else
      render :edit
    end
  end

  def create
  	@recipe = Recipe.new(recipe_params)
  	@recipe.user_id = current_user.id
  	if @recipe.save
  	  redirect_to recipe_path(@recipe), notice: "投稿に成功しました！"
    else
      render :new
    end
  end

  def new
  	@recipe = Recipe.new
    @recipe.recipe_images.build
  end

  def destroy
    recipe = Recipe.find(params[:id])
    recipe.destroy
    redirect_to recipes_path
  end


  private
  def recipe_params
  	params.require(:recipe).permit(:title, :body, recipe_images_images: [])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
  	@users = User.all
  end

  def show
  	@user = User.find(params[:id])
  end

  def edit
  	@user = User.find(params[:id])
    if @user != current_user
      redirect_to users_path, alert: "不正なアクセスです！"
    end
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  	  redirect_to user_path(@user), notice: "更新に成功しました！"
    else
      render :edit
    end
  end


  private
  def user_params
  	params.require(:user).permit(:name, :email, :profile, :profile_image, :profile_bg_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>harahetter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/3a4e43d077.js" crossorigin="anonymous"></script>
  </head>

  <body id="<%= controller.controller_name %>-<%= controller.action_name %>">
    <nav class="navbar navbar-expand-lg navbar-light">
      <%= link_to image_tag("harahetter-logo.png"), root_path, class: "navbar-brand" %>
      <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#Navber" aria-controls="Navber" aria-expanded="false" aria-label="ナビゲーションの切替">
        <span class="navbar-toggler-icon"></span>
      </button>
      <% if user_signed_in? %>
      <div class="collapse navbar-collapse" id="Navber">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <%= link_to "マイページ", user_path(current_user), class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "ハラヘッター民", users_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "新規投稿", new_recipe_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "ハラヘリメニュー", recipes_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        </ul>
      </div>
      <% else %>
      <div class="collapse navbar-collapse" id="Navber">
        <ul class="navbar-nav ml-auto">

          <li class="nav-item">
            <%= link_to "ハラヘッター民", users_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "ハラヘリメニュー", recipes_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "ログイン", new_user_session_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "新規登録", new_user_registration_path, class: "nav-link" %>
          </li>
        </ul>
      </div>
      <% end %>
    </nav>

    <% if flash[:notice] %>
      <div class="alert alert-primary" role="alert"><strong><%= notice %></strong></div>
    <% end %>

    <% if flash[:alert] %>
      <div class="alert alert-danger" role="alert"><strong><%= alert %></strong></div>
    <% end %>

    <%= yield %>

    <footer class="footer-navbar">
      © All rights reserved by harahetter.
    </footer>
  </div>
  </body>
</html>